-- 코드를 입력하세요
SELECT 
    T.MEMBER_ID, 
    T.MEMBER_NAME, 
    T.GENDER, 
    DATE_FORMAT(T.DATE_OF_BIRTH, '%Y-%m-%d') AS DATE_OF_BIRTH 
FROM MEMBER_PROFILE AS T
WHERE MONTH(T.DATE_OF_BIRTH) = 3 
  AND T.GENDER = 'W' 
  AND T.TLNO IS NOT NULL
ORDER BY T.MEMBER_ID ASC;