-- 코드를 작성해주세요
-- 편자 = 분화된 연도별 가장 큰 대장균 크기 - 각 대장균의 크기
-- 정렬 = 연도 오름차순, 대장균의 크기 편자 오름차순

SELECT YEAR(A.DIFFERENTIATION_DATE) AS YEAR, (B.MAX_SIZE-A.SIZE_OF_COLONY) AS YEAR_DEV, A.ID
FROM ECOLI_DATA A
LEFT JOIN (
    SELECT  YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM  ECOLI_DATA
    GROUP BY  YEAR(DIFFERENTIATION_DATE)
) B
ON  YEAR(A.DIFFERENTIATION_DATE) = B.YEAR
ORDER BY YEAR, YEAR_DEV

